from __future__ import annotations

import argparse
import sys
from pathlib import Path

from autopilot.config import load_settings
from autopilot.tools.bash import BashRunner
from autopilot.tools.environments import default_environment_catalog


def _script_text(name: str, commands: list[str]) -> str:
    body = "\n".join(commands).rstrip() + "\n"
    return f"#!/usr/bin/env bash\n# Generated by autopilot-install-env for environment: {name}\n{body}"


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate or run installation scripts for configured runtime environments such as vllm.")
    parser.add_argument("environment", nargs="?", default="vllm", help="Environment name/id from runtime.environments. Default: vllm.")
    parser.add_argument("--config", default=None, help="YAML config path. Default: AUTOPILOT_CONFIG or ./autopilot.yaml if present.")
    parser.add_argument("--env-file", default=None, help="Optional .env file path for backwards compatibility.")
    parser.add_argument("--output-script", default=None, help="Where to write the install script. Default: scripts/install_<environment>_env.sh")
    parser.add_argument("--execute", action="store_true", help="Actually run the generated install script. Default only writes/prints it.")
    parser.add_argument("--dry-run", action="store_true", help="Print the script and exit without writing or executing.")
    parser.add_argument("--cwd", default=".", help="Working directory when executing the script.")
    parser.add_argument("--timeout", type=float, default=7200.0, help="Install command timeout in seconds.")
    parser.add_argument("--verify", action="store_true", help="Run verify_commands after installation if configured. Requires --execute.")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    settings = load_settings(config_file=args.config, env_file=args.env_file)
    env = settings.environment_registry().get(args.environment)
    if env is None:
        names = ", ".join(settings.environment_registry().names()) or "none"
        print(f"[error] Unknown environment {args.environment!r}. Known environments: {names}", file=sys.stderr)
        return 2
    commands = list(env.install_commands)
    if not commands:
        # Configs often alias `vllm` to a site-specific serving env such as
        # `lapha-beta` without install commands. For install-script generation,
        # fall back to the built-in catalog for the same environment id.
        for default_env in default_environment_catalog():
            if default_env.id == env.id and default_env.install_commands:
                commands = list(default_env.install_commands)
                break
    if not commands:
        print(f"[error] Environment {env.name!r} has no install_commands in config/default catalog.", file=sys.stderr)
        return 2
    text = _script_text(env.name, commands)
    script_path = Path(args.output_script or f"scripts/install_{env.name}_env.sh")
    if args.dry_run:
        print(text, end="")
        return 0
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text(text, encoding="utf-8")
    script_path.chmod(0o755)
    print(f"[done] wrote install script: {script_path}")
    print(f"[info] environment: {env.name}")
    print(f"[info] activation: {env.activation_command() or 'not configured'}")
    if not args.execute:
        print("[info] not executing. Add --execute to run it on this machine.")
        return 0
    runner = BashRunner(cwd=args.cwd, timeout=args.timeout)
    result = runner.run(str(script_path), shell=True, timeout=args.timeout)
    print(result.stdout, end="")
    if result.stderr:
        print(result.stderr, file=sys.stderr, end="")
    if not result.ok:
        print(f"[error] install failed: returncode={result.returncode}, timed_out={result.timed_out}", file=sys.stderr)
        return 1
    if args.verify and env.verify_commands:
        for command in env.verify_commands:
            print(f"[info] verify: {command}")
            verify = runner.run(command, shell=True, timeout=min(args.timeout, 600.0))
            print(verify.stdout, end="")
            if verify.stderr:
                print(verify.stderr, file=sys.stderr, end="")
            if not verify.ok:
                print(f"[error] verify failed: returncode={verify.returncode}", file=sys.stderr)
                return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
